baseURL = "/"
languageCode = "en-us"
title = "dotKuro"

[author]
    name = "Alexander Kampf"

[params]
    description = "Personal website by Alexander \"dotKuro\" Kampf"
    keywords = "computer science yugioh programming"
    images = ""

    homeSubtitle = "Programmer and TCG Lover"

[params.logo]
    logoText = "> dotKuro$ cd ~"
    logoColor = "#aa2040"

[[params.social]]
    name = "github"
    url = "https://github.com/dotKuro"

[[params.social]]
    name = "email"
    url = "mailto:akampftcg@gmail.com"

[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/dotKuro1337"


[[menu.main]]
    name = "whoami"
    identifier = "about"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "CV"
    identifier = "cv"
    url = "/cv/web"
    weight = 2
