version: "3.8"

# Only needed for traefik deployment
networks:
  http_network:
    external: true

services:
  dotkuro-nginx-prod:
    build: .
    # Deployment with dedicated port
    #ports:
    #  - 80:80
    # Deployment with traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls.certresolver=myresolver"
      - "traefik.docker.network=http_network"
      - "traefik.http.services.website.loadbalancer.server.port=80"
    networks:
      - http_network

